# Generated by Django 5.2.4 on 2025-07-14 06:29

import django.core.validators
import kb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_comment_is_active_department_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=kb.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
