# Generated by Django 5.2.4 on 2025-07-15 06:46

from django.db import migrations
from django.utils.text import slugify
import time

def generate_slugs(apps, schema_editor):
    Document = apps.get_model('kb', 'Document')
    for doc in Document.objects.filter(slug=''):
        base_slug = slugify(doc.title)
        unique_slug = base_slug
        timestamp = int(time.time())
        while Document.objects.filter(slug=unique_slug).exists():
            unique_slug = f"{base_slug}-{timestamp}"
            timestamp += 1
        doc.slug = unique_slug
        doc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_document_file_document_slug'),  # ← Это ваша последняя миграция
    ]

    operations = [
        migrations.RunPython(generate_slugs),
    ]
