# Generated by Django 5.2.4 on 2025-07-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_auto_20250715_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
